### ISSUE TITLE
Plugin posting wrong url on Discord

### ISSUE THREAD

**Issue by randornclawyer** [pvyParts/allianceauth-signal-pings#3]
When a Fleet is pinges, the Plugins Posts a link myauth.url/optimers/

Allianceauth gives a Page does not exist. If you believe this is in error please contact the administrators. (404 Page Not Found) Error.
The correct Url has to be myauth.url/optimer/ - without the s to the end ..

**Comment by pvyParts** [comment]
Do you have v0.0.6?

**Comment by pvyParts** [comment]
Was fixed previously and I can't recreate
